import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ReduxProvider } from "@/lib/redux/provider";
import React from "react";
import { Toaster } from 'react-hot-toast';
import { AuthProvider } from "@/components/context/AuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} w-screen h-screen bg-[#fafafa]`}>
        <ReduxProvider>
          <AuthProvider>
            {children}
            <Toaster position="bottom-right" reverseOrder={false} />
          </AuthProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
